version: '3'
services:
  enviro:
    image: phriscage/iot_gpio-enviro
    devices:
      - /dev/mem
      - /dev/i2c-1
    privileged: true
    command: python app.py
    deploy:
      mode: global
      placement:
        constraints:
          - node.role != manager
