version: '3'
services:
  enviro:
    image: phriscage/iot_gpio-enviro
    #cap-add:
      #- SYS_RAWIO
    #devices:
      #- /dev/mem
    privileged: true
    command: python app.py
    deploy:
      mode: global
      placement:
        constraints:
          - node.role != manager
